# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ธรรมสุตตะ พระไตรปิฎก # หรือชื่อเว็บไซต์ที่คุณต้องการ
description: "เว็บไซต์รวบรวมคำสอนในพระพุทธศาสนา พระไตรปิฎก พระอภิธรรม และธรรมะต่างๆ" # คำอธิบายเว็บไซต์ของคุณ
author:
  name: "ธัมมสุตตะ" # หรือชื่อผู้จัดทำ
  # email: "your-email@example.com" # ใส่อีเมลถ้าต้องการ

# Base URL
# The subpath of your site, e.g. /blog
# IMPORTANT: for GitHub Project Pages, set this to '/your-repository-name'
baseurl: "/tripitaka"

# URL
# The base hostname & protocol for your site, e.g. http://example.com
# IMPORTANT: for GitHub Project Pages, set this to 'https://your-username.github.io'
url: "https://dhamsutta.github.io"

# Build settings
markdown: kramdown
# theme: minima # ถ้าคุณไม่ได้ใช้ธีมใดๆ เลย หรือใช้ธีมเริ่มต้นของ Jekyll (Minima)
               # ถ้าคุณใช้ Minimal Mistakes เป็น gem คุณอาจจะต้องใส่ theme: minimal-mistakes-jekyll
               # แต่ถ้าคุณ copy ไฟล์ธีมมาใส่ใน repo เอง ก็อาจจะไม่ต้องตั้งค่า theme ตรงนี้

# Include custom directories/files to be processed by Jekyll
include:
  - "_pages" # ทำให้ Jekyll ประมวลผลไฟล์ในโฟลเดอร์ _pages แน่นอน

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
